version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Europe/Stockholm
    groups:
      docker:
        patterns:
          - "**"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Europe/Stockholm
    groups:
      github-actions:
        patterns:
          - "**"
  - package-ecosystem: pip
    insecure-external-code-execution: allow
    directory: "/"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Europe/Stockholm
    groups:
      pip:
        patterns:
          - "**"