# Generated by Django 6.0.2 on 2026-03-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("country_code", models.CharField(max_length=2)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            options={
                "db_table": "airports",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("outbound_airport", models.CharField(max_length=3)),
                ("inbound_airport", models.CharField(max_length=3)),
                ("outbound_date", models.DateField()),
                ("inbound_date", models.DateField()),
                ("price", models.IntegerField()),
                ("normal_price", models.IntegerField()),
                ("discount", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "trips",
                "ordering": ["price", "outbound_date"],
                "indexes": [
                    models.Index(
                        fields=["outbound_date", "inbound_date"],
                        name="trips_outboun_7ce2ca_idx",
                    ),
                    models.Index(fields=["price"], name="trips_price_f79136_idx"),
                ],
            },
        ),
    ]
